sudo: required
dist: trusty
group: edge

language: node_js

os:
  - linux

node_js:
  - '6'
  - '5'
  - '4'

env:
  global:
    - secure: "NIUdt5dET7v1C7rWLN/I77EXe7kSUuTg7Za0m09R8ztG8QVx8lCa8n6v8XyjtS21Lm5b32DAAs4hV8/jTFp7IKRTP1M2vRUbwMTrUnObKILC0CmUQs+A0dTzgyhyBa35UVFbR9+Qh4abdzAYyS/OX1cYt7B5iO5QNDB4MQ5i565wY4LS8HDL6KsgxMDIeb5bzjVbz+OicpZVvyXj8lOmtTIs81MkOdRJ8PnwAbS79I1LpqPGoIw1zBfArjMEzyuQzOunNWTUPb7SwAJtUqkQqP8+GaLOehYWdJxQXboSHZqOJgMaqHCVVP9Pw8nWLi6N61xRVqoQg1TnWRjQFy5l4ikddxvhl1JWMQhse6z6BbDPLkDZvgyNEvb1MnWmEe9qmSuqAzfx2PzbVPbNyRcPRHFzSS2gNFlINNPurykE8g79bHvWtTzY9uHJ2ICKR92DlCG36tsVlq1ZSBw3GNqgXJEN+iR+iQk1Y4m9GhdLgJxvpAMgyiHMZV6ncXQNavOFEs5UlLprdybVxAs9rG2RevWQq1QmsAwi1sMO8OfePmyKuYxuuFOjWPmvxfCDdARmMxHK17ZduMw4SDlmnyDzA27GQ4m21gg8Fl0Xt047DpgiIcFFjsLbDfIoCD91STLLlWQDGeGQHJDgs7GRyyRTme8+uAgMqD5u5/GnzKBBBIs=" # GITHUB_TOKEN

before_install:
  - npm install -g npm
  - npm --version

install:
  - npm install

after_success:
  - mkdir -p releases
  - PACKAGE_NAME=`scripts/package-name.sh package.json`
  - PACKAGE_VERSION=`scripts/package-version.sh package.json`
  - RELEASE=${PACKAGE_NAME}-${PACKAGE_VERSION}
  - COMMIT_LOG=`git log -1 --format='%ci %H %s'`
  - COMMIT_HASH=`git log -1 --format="%h"`
  - |
    if [[ "$TRAVIS_NODE_VERSION" == "6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      pushd releases;
      ln -sf ../src ${RELEASE};
      zip -r ${RELEASE}.zip ${RELEASE};
      popd;
      ls -al releases/*;
      if [[ -z "$TRAVIS_TAG" ]]; then
        mv "releases/${RELEASE}.zip" "releases/${RELEASE}-${COMMIT_HASH}.zip";
        npm run github-release -- delete \
          --owner=cncjs \
          --repo=cncjs-shopfloor-tablet \
          --tag="latest" \
          --name="${TRAVIS_BRANCH}" \
          "*.zip";
        npm run github-release -- upload \
          --owner=cncjs \
          --repo=cncjs-shopfloor-tablet \
          --tag="latest" \
          --name="${TRAVIS_BRANCH}" \
          --body="${COMMIT_LOG}" \
          "releases/${RELEASE}-${COMMIT_HASH}.zip";
      fi
    fi

before_deploy:
  - echo "Deploying to GitHub releases"
  - ls -al releases

deploy:
  provider: releases
  api_key:
    secure: "pQINRWiGWO7aDHyoSL42m4wrICKzGxS1C9BLK+gc9L9PO1Wjx9NYIdF4q20L1BhGY27QPdqTGc/ODPU9zzec5yp2om/V0n7BhrkPGHDJJk99m36YIREfxR0yq0fJJv50oFB84V13pCu4u/ZD++DopVr6mHRaGSuSM8QquviWmwrj7gtFvsIegjSHmNijp/R9KI3Ogd28NbA1sR23e3YxxFH7GDvDrsXCUc+k9JxILktXwMF6jzCxA0AFFXBdkw4PLy0M45/6aiUbq7I8giFfLq6WLTzUzJSDHnuWC3FmjHObKZIZZ5ugDgQvREZL1OUUIVaIi5h6EHJOiil79CD6s2Lh1EvrCCkdEfkQjSnzO4WZ7cuuAJE8v2nPMb8Oc0Miz0turzHNNsuKJhIf/g9lCCEsbLJz1uGDrgdrQyB171/3TiVTC9a9PFb4dgzfoum8XNeNqBtJd3a3DCM70iZDvSpL9A/sYmA1298eD5v+UGk7HpncjhUtPICecSdvYtdUXuqu+/0zHSasZIGvSZuiJVh0DM+gTeEAm8kUB1cD2vICHMSzlDFyMVB9S1KgLsEUawKq2v6C6Cs6J1YASQIx09LfMZBcJLxShjwqtgwlJ4iuSJt/AoLCm/95LDet2g7D8+iAUzTWshVjsn8TW0GafAxiQ2wxReUjzjBmvIDFykQ="
  file_glob: true
  file:
    - 'releases/*.*'
  overwrite: true
  skip_cleanup: true
  on:
    # https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on
    tags: true  # Deploy app only when a tag is applied to the commit
    node: '6'
